# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-24 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0128_remove_node_preprint_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abstractnode',
            options={'base_manager_name': 'objects', 'permissions': (('view_node', 'Can see node details in the admin app'), ('read_node', 'Can read the node'), ('write_node', 'Can write the node'), ('admin_node', 'Can manage the node'))},
        ),
    ]
